
# pull configuration from router to this repository
pull:
	ssh microtik /export file=router.rsc
	scp microtik:router.rsc .

# does not really work yet
push:
	echo "not implemented"
#	scp router.rsc microtik:
#	ssh microtik /import file=router.rsc
